data = [("b", 2), ("a", 2), ("c", 1), ("d", 2)]
print(sorted(data, key=lambda t: t[1]))
print(sorted([3, 1, 2], reverse=True))
print(sorted("dcba"))
print(sorted([1, 2, 3], key=lambda x: -x))
print(min([3, 1, 2]), max([3, 1, 2]))
print(min("hello", key=lambda c: ord(c)))
print(max([("a", 1), ("b", 3), ("c", 2)], key=lambda t: t[1]))
print(min([], default=42), max([], default=-1))
print(min(5, 3, 8, 1), max(5, 3, 8, 1))
print(sum([1, 2, 3]), sum([1, 2, 3], 10))
print(sum([[1], [2]], []))
print(any([0, 0, 1]), any([0, 0]), all([1, 1, 1]), all([1, 0]))
print(any([]), all([]))
