print(bool(0), bool(1), bool(""), bool("a"), bool([]), bool([1]))
print(int("42"), int(3.9), int("ff", 16), int("101", 2))
print(float("3.14"), float(5), float("inf"))
print(str(42), str(3.14), str([1, 2]))
print(list("abc"), list((1, 2, 3)), list(range(3)))
print(tuple([1, 2, 3]), tuple("ab"))
print(dict([("a", 1), ("b", 2)]))
print(dict(x=1, y=2))
print(sorted(set([3, 1, 2, 1, 3])))
print(sorted(set("hello")))
print(type(1).__name__, type("a").__name__, type([]).__name__)
print(type(1.0).__name__, type({}).__name__, type(None).__name__)
print(callable(len), callable(print), callable(42), callable(lambda: 1))
print(callable(int), callable("str"))
