print("hi".center(10))
print("hi".center(10, "*"))
print("hi".center(1))
print("hi".ljust(6, "."))
print("hi".rjust(6, "."))
print("hi".ljust(6))
print("hi".rjust(6))
print("42".zfill(5))
print("-42".zfill(5))
print("+42".zfill(5))
print("abc".zfill(2))
print("a\tb\tc".expandtabs())
print("a\tb\tc".expandtabs(4))
print("ab\tc".expandtabs(4))
