print("  hi  ".strip())
print("  hi  ".lstrip())
print("  hi  ".rstrip())
print("xxhixx".strip("x"))
print("xyxhixyx".strip("xy"))
print("..hi..".lstrip("."))
print("a,b,c".split(","))
print("a,b,c".split(",", 1))
print("a b  c".split())
print("a,b,,c".split(","))
print("a,b,c".rsplit(",", 1))
print("one\ntwo\nthree".splitlines())
print("a\r\nb\rc".splitlines())
print("a\nb\n".splitlines())
print("a\nb".splitlines(True))
print("-".join(["a", "b", "c"]))
print("".join(["x", "y"]))
print(",".join([]))
