s = "Hello World"
print(s.upper())
print(s.lower())
print(s.swapcase())
print("hello world foo".title())
print("hello world".capitalize())
print("HELLO".capitalize())
print("".upper())
print("abc DEF".title())
print("it's a test".title())
print("123abc".capitalize())
print("MixedCase".swapcase())
print("ÀÉÎ".lower())
print("àéî".upper())
