print("a=b=c".partition("="))
print("a=b=c".rpartition("="))
print("abc".partition("="))
print("abc".rpartition("="))
print("key: value".partition(": "))
print("TestHook".removeprefix("Test"))
print("TestHook".removeprefix("Xyz"))
print("filename.txt".removesuffix(".txt"))
print("filename.txt".removesuffix(".py"))
print("".removeprefix("a"))
print("aXbXc".partition("X"))
print("aXbXc".rpartition("X"))
