s = "あいうえお"
print(len(s))
print(s[0])
print(s[1:3])
print(s[::-1])
print(s[-1])
print(len("あいう"))
print("café"[3])
print(len("café"))
print("😀😁😂"[1])
print(len("😀😁😂"))
print("漢字テスト".upper())
print("あ" * 3)
print("あいう".count("い"))
print("いう" in "あいうえお")
print("あ,い,う".split(","))
