print("123".isdigit(), "12a".isdigit(), "".isdigit())
print("abc".isalpha(), "ab1".isalpha(), "".isalpha())
print("abc123".isalnum(), "abc 1".isalnum(), "".isalnum())
print("   ".isspace(), " a ".isspace(), "".isspace())
print("abc".islower(), "Abc".islower(), "123".islower())
print("ABC".isupper(), "Abc".isupper(), "123".isupper())
print("Hello World".istitle(), "Hello world".istitle(), "HELLO".istitle())
print("hello".isidentifier(), "_x1".isidentifier(), "1x".isidentifier())
print("def".isidentifier(), "a b".isidentifier())
print("\t\n".isspace())
print("Title Case".istitle())
